# Generated by Django 6.0.1 on 2026-01-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restockbatch',
            name='cost_per_pair',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost at time of purchase', max_digits=10, null=True),
        ),
    ]
