# Generated by Django 6.0.1 on 2026-01-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_restockbatch_cost_per_pair'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossSheet',
            fields=[
            ],
            options={
                'verbose_name': 'Boss Sheet / Report',
                'verbose_name_plural': 'Boss Sheet / Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.sale',),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='buy_price_at_moment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale_price_at_moment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
