# Generated by Django 6.0.1 on 2026-01-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_bosssheet_alter_sale_total_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BossSheet',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='restockbatch',
            options={'verbose_name_plural': 'Restock Batches'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff Members'},
        ),
        migrations.AlterField(
            model_name='product',
            name='current_buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='restockbatch',
            name='cost_per_pair',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
