# Generated by Django 6.0.1 on 2026-01-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_code_product_gender_product_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restockbatch',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Number of units added (pairs / bags / boxes)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restockbatch',
            name='unit',
            field=models.CharField(choices=[('pairs', 'Pairs'), ('bags', 'Bags'), ('boxes', 'Boxes')], default='pairs', max_length=10),
        ),
        migrations.AlterField(
            model_name='restockbatch',
            name='quantity_added',
            field=models.PositiveIntegerField(editable=False, help_text='Total pairs added (auto-calculated)'),
        ),
    ]
