# Generated by Django 6.0.1 on 2026-01-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_restockbatch_quantity_restockbatch_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='quantity_added',
            field=models.PositiveIntegerField(default=123, editable=False, help_text='Total pairs added (auto-calculated)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of units added (pairs / bags / boxes)'),
        ),
    ]
