# Generated by Django 6.0.1 on 2026-01-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_saleitem_quantity_added_alter_saleitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='unit',
            field=models.CharField(choices=[('pairs', 'Pairs'), ('bags', 'Bags'), ('boxes', 'Boxes')], default='pairs', max_length=10),
        ),
    ]
