# Generated by Django 6.0.1 on 2026-01-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_saleitem_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='quantity_added',
        ),
    ]
