# Generated by Django 6.0.1 on 2026-01-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_saleitem_quantity_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter percentage (e.g. 10 for 10% off)', max_digits=5),
        ),
    ]
